Migrate logs repo from travisCI to GitHub actions
aws-cloudformation/aws-cloudformation-resource-providers-logs pull request #54
Opened 2021-01-08 21:02 UTC by jotompki

*Issue #, if available:*

*Description of changes:*  Migrates the travis continuous integration jobs to GitHub actions. Similar to: https://github.com/aws-cloudformation/aws-cloudformation-resource-schema/pull/108.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-08 21:05 UTC, jotompki commented on .github/workflows/pr-ci.yml
> +          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify || travis_terminate 1
```suggestion
          mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B clean verify
```

2021-01-08 21:32 UTC, sungkkim approved these changes

2021-01-08 21:49 UTC, omkhegde approved these changes

2021-01-08 22:01 UTC, PatMyron requested changes
hundreds of [`aws-cloudformation-resource-providers`](https://github.com/aws-cloudformation/?q=aws-cloudformation-resource-providers-) repos to migrate and we've already gone through a lot of CI PR churn for them (all of @miparnisari's PRs to make sure Maven builds run instead of just `pre-commit` formatting, switching between CodeBuild, Travis, Github Actions, etc), so let's migrate all of them together

I'd prefer if we took the chance to improve these before starting to manually migrate hundreds of repos one-by-one. These should also be running [`cfn validate` and `cfn submit --dry-run` at the very least and arguably `cfn test`](https://github.com/aws-cloudformation/cloudformation-cli) and [`git-secrets`](https://github.com/awslabs/git-secrets) as well

2021-01-15 22:25 UTC, jotompki commented
> hundreds of [`aws-cloudformation-resource-providers`](https://github.com/aws-cloudformation/?q=aws-cloudformation-resource-providers-) repos to migrate and we've already gone through a lot of CI PR churn for them (all of @miparnisari's PRs to make sure Maven builds run instead of just `pre-commit` formatting, switching between CodeBuild, Travis, Github Actions, etc), so let's migrate all of them together
> 
> I'd prefer if we took the chance to improve these before starting to manually migrate hundreds of repos one-by-one. These should also be running [`cfn validate` and `cfn submit --dry-run` at the very least and arguably `cfn test`](https://github.com/aws-cloudformation/cloudformation-cli) and [`git-secrets`](https://github.com/awslabs/git-secrets) as well

Doing a quick spot check it appears only 12/38 public resource provider repositories have a travis build job. All for automation of this process but we would probably have to schedule some dedicated work to do a big overhaul. 

The process of team commits to repo -> travisCI build doesn't work -> looks to documentation as to why -> sees example github action -> upgrades doesn't seem too bad for now.

2021-01-15 23:06 UTC, PatMyron commented
> Doing a quick spot check it appears only 12/38 public resource provider repositories have a travis build job

Only a dozen repos even meeting our best practices from 2019 feels like even more reason to centralize the process longterm

2022-03-16 18:34 UTC, miparnisari approved these changes

2022-10-17 17:42 UTC, markkuhn commented
This PR has been open for more than a year. Can we close it?

2022-11-21 18:46 UTC, closed without merging